/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DefaultApi
import org.openapitools.client.models.HTTPValidationError

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test handleFileUploadUploadfilePost
        should("test handleFileUploadUploadfilePost") {
            // uncomment below to test handleFileUploadUploadfilePost
            //val file : kotlin.collections.List<java.io.File> = /path/to/file.txt // kotlin.collections.List<java.io.File> | 
            //val result : kotlin.Any = apiInstance.handleFileUploadUploadfilePost(file)
            //result shouldBe ("TODO")
        }

        // to test readRootGet
        should("test readRootGet") {
            // uncomment below to test readRootGet
            //val result : kotlin.Any = apiInstance.readRootGet()
            //result shouldBe ("TODO")
        }

    }
}
