/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.ValidationError

class HTTPValidationErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HTTPValidationError
        //val modelInstance = HTTPValidationError()

        // to test the property `detail`
        should("test detail") {
            // uncomment below to test the property
            //modelInstance.detail shouldBe ("TODO")
        }

    }
}
